import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from './LoginBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import LogoutBtn from './LogoutBtn'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log(session)


  

  let cooks = cookies().get('name')
  console.log('쿠키',cooks)

  return (
    <html>
      <body>
      <div className="navbar"> 
  <Link href="/" className="logo">Leeforum</Link> 
  <Link href="/list">List</Link>
{
  !session ? <LoginBtn />: <span>{session.user.name}님 <LogoutBtn/></span>
}
</div>  
        {children}</body>
    </html>
  )
}
